{
    "ParentLink": {
        "Property": "risks",
        "Target": {
            "EntitySet": "Risks",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/RisksMobile/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/RisksMobile/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "createdAt": "#Page:Risks_CreateMitigations/#Control:createdAt/#Value",
        "createdBy": "#Page:Risks_CreateMitigations/#Control:createdBy/#Value",
        "description": "#Page:Risks_CreateMitigations/#Control:description/#Value",
        "owner": "#Page:Risks_CreateMitigations/#Control:owner/#Value",
        "timeline": "#Page:Risks_CreateMitigations/#Control:timeline/#Value"
    },
    "Target": {
        "EntitySet": "Mitigations",
        "Service": "/RisksMobile/Services/RiskManagementService.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}